### PR TITLE
private events project.

### PR DESCRIPTION
**Pull request by Leon-Mbegera**
This is a site similar to  Eventbrite which allows users to:
-  Visiting users can only view created events
- Logged in users can attend created events
- A logged-in user can even see details of a particular event, together with its attendees.

### CODE REVIEW

**Review by george-shammar — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUIRED** :recycle: :recycle: 

**Highlight**

- [x] Your repo looks professional without linter errors.
- [x] You followed the correct gitflow.
- [x] And you have a good README.
Good job. :+1: 

Please see below required changes.

- [x] Somewhere in your README is making reference to Member's Only project. Please correct it.
- [x] Your app should have a functional login page (authentication should be handled with devise with an Email, Password, and Password confirmation fields for User creation. There is nowhere to login to the app.
- [x] After successful sign in, a user should be redirected to the Event's index page (set to root_path in the Routes file).
- [x] Logged in user should be able to create new event. 
- [x] Event's index page should display past and upcoming events lists. I cannot create an event at the moment.
- [ ] The event's show page should display the list of attendants. I cannot create an event at the moment.
- [ ] The user's show page should display events the user has created and events that the user is attending to be separated in past and upcoming.
- [x] Navigation links should be present at the top of the page.
- [ ] Event model should have creation date as attribute.
- [ ] Event model should have scope for upcoming events.
- [ ] Event model should have scope for past events.
- [x] Events index controller action should list past events, i.e. @past_events = Event.previous_events.
- [x] Events index controller action should list upcoming events, i.e. @upcoming_events = Event.upcoming_events.
- [x] User Controller show action should list events created by user, i.e. @created_events = current_user.events.
- [x] User Controller show action  should list events previously attended by user using event model scope, i.e. @past_events = current_user.attended_events.previous.
- [x] User controller show action should list upcoming events previously attended by user using event model scope, i.e. @upcoming_events = current_user.attended_events.upcoming.
- [ ] Please test your application for validations, associations and integration. Make use of Rspec and Capybara. Model must have unit tests for validations and associations. Authentication must have integration tests. Event management features must have integration tests. 

Please make the above required changes and submit another CRR when you're ready.

Drop your message here if you need further clarification or help.

Cheers and happy coding. :smile:

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :red_circle: :stop_sign: 
------------------
Hello @Leon-Mbegera  great job you are doing in this project :+1: :clap: 
However, there are a few changes to make to complete this project :hammer_and_wrench: see them below :eyes: :point_down: 
--------------
- [x] Please add a link to the root page. The only way a can go to the root page is with the signup or sign in but those links should be redirected to the signup or sign in. Please fix this. 
- [x] Once you are login you should see only the link to `Sign out`. Please fix this. 
To accomplished this inside `application.html.erb`  change the if statement you have with the following if statement. 

`<% if user_signed_in? %>
            <%= link_to current_user.email, current_user, class: "nav-item px-3 text-dark fw-bold text-decoration-none" %>
            <li><%= link_to "Sign out", destroy_user_session_path, method: "delete", class: "nav-item px-3 text-dark fw-bold text-decoration-none" %></li>
            <% else %>
            <li><%= link_to "Sign up", new_user_registration_path, class: "nav-item px-3 text-dark fw-bold text-decoration-none"%></li>
          <li><%= link_to "Log in", new_user_session_path, class: "nav-item px-3 text-dark fw-bold text-decoration-none" %></li>
          <% end %>`
- [x] There must be a link to the event's show page where I can see a list of attendants. 
- [x] I can attend the same event more than one time. Please fix this I only can be able to attend one time. 
- [x] Before the step `rails db:migrate` you need to create the database `rails db:create`
- [x] Please add on your readme file after the `rails server` where they need to go. `http://localhost:3000`
----------------
Please make these required changes and send it again for another review :muscle: :+1: 
HAPPY CODING!!!

**Review by george-shammar — APPROVED** [review]
### **STATUS: APPROVED** :heavy_check_mark: :heavy_check_mark: 

@Leon-Mbegera , Thank you for making the required changes.

- [x] Your app works fine and your repo looks professional as well.

I'm happy to approve this project.

I wish you good luck in your future projects.

Cheers :smile:

**Comment by Leon-Mbegera** [comment]
All requested changes are addressed.
Gracias`.

**Pull request merged**
